- name: Install FTP server
  apt:
    name: "{{ ftp_package }}"
    state: present

- name: Copy vsftpd config
  template:
    src: vsftpd.conf.j2
    dest: "{{ ftp_config_path }}"
    owner: root
    group: root
    mode: '0644'
  notify: Restart FTP server

- name: Ensure FTP server is running and enabled
  service:
    name: "{{ ftp_service }}"
    state: started
    enabled: yes

- name: Get data user password
  onepassword.connect.field_info:
    token: "{{ connect_token }}"
    item: ftp-data
    field: password
    vault: "{{ ansible_vault }}"
  no_log: false
  register: data_pwd

- name: Add the user 'data'
  ansible.builtin.user:
    name: data
    comment: Data User
    group: data
    groups: jellyfin
    shell: /bin/bash
    home:  "/data"
    password: "{{ data_pwd.field.value | password_hash('sha512') }}"