- name: Create a group for media
  group:
    name: jellyfin

- name: Ensure Jellyfin config directory exists
  file:
    path: "{{ jellyfin_config_dir }}"
    state: directory
    owner: root
    group: jellyfin
    mode: '0775'

- name: Ensure /data is mounted and available
  stat:
    path: /data
  register: data_dir

- name: Fail if /data is not a Btrfs mount
  fail:
    msg: "/data must be a mounted Btrfs filesystem"
  when: not data_dir.stat.exists

- name: Create Btrfs subvolume
  command: "btrfs subvolume create /data/{{ btrfs_subvolume }}"
  args:
    creates: "/data/{{ btrfs_subvolume }}"

- name: Ensure Jellyfin directory has correct ownership
  file:
    path: "/data/{{ btrfs_subvolume }}"
    state: directory
    owner: root
    group: jellyfin
    mode: '0775'

- name: Create media directory
  file:
    path: "/data/{{ btrfs_subvolume }}/media"
    state: directory
    owner: root
    group: jellyfin
    mode: '0775'

- name: Create media directory
  file:
    path: "/data/{{ btrfs_subvolume }}/media/movies"
    state: directory
    owner: root
    group: jellyfin
    mode: '0775'

- name: Create media directory
  file:
    path: "/data/{{ btrfs_subvolume }}/media/shows"
    state: directory
    owner: root
    group: jellyfin
    mode: '0775'

- name: Copy Docker Compose file
  copy:
    src: docker-compose.yaml
    dest: "{{ jellyfin_config_dir }}/docker-compose.yaml"
    mode: '0644'

- name: Start Jellyfin container with Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ jellyfin_config_dir }}"
    state: present

- name: Add users to jellyfin group
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups: jellyfin
    append: yes
  loop: "{{ jellyfin_users }}"

- name: Download Jellyfin GPG key
  get_url:
    url: https://repo.jellyfin.org/jellyfin_team.gpg.key
    dest: /etc/apt/trusted.gpg.d/jellyfin.asc
    mode: '0644'
  
- name: Add Jellyfin repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/jellyfin.asc] https://repo.jellyfin.org/ubuntu {{ ansible_distribution_release | lower }} main"
    state: present

- name: Update APT again after adding Docker repo
  apt:
    update_cache: yes

- name: Instal HW drivers
  apt:
    name:
      - jellyfin-ffmpeg7
      - intel-opencl-icd
    state: present
  