- name: Ensure Jellyfin config directory exists
  file:
    path: "{{ jellyfin_config_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy Docker Compose file
  copy:
    src: docker-compose.yml
    dest: "{{ jellyfin_config_dir }}/docker-compose.yml"
    mode: '0644'

- name: Start Jellyfin container with Docker Compose
  community.docker.docker_compose:
    project_src: "{{ jellyfin_config_dir }}"
    state: present