- name: Create a group for media
  group:
    name: jellyfin

- name: Ensure Jellyfin config directory exists
  file:
    path: "{{ jellyfin_config_dir }}"
    state: directory
    owner: root
    group: jellyfin
    mode: '0775'

- name: Ensure Jellyfin data directory exists
  file:
    path: /data/jellyfin
    state: directory
    owner: root
    group: jellyfin
    mode: '0775'

- name: Create media directory
  file:
    path: /data/jellyfin/media
    state: directory
    owner: root
    group: jellyfin
    mode: '0775'

- name: Create media directory
  file:
    path: /data/jellyfin/media/movies
    state: directory
    owner: root
    group: jellyfin
    mode: '0775'

- name: Create media directory
  file:
    path: /data/jellyfin/media/shows
    state: directory
    owner: root
    group: jellyfin
    mode: '0775'


- name: Copy Docker Compose file
  copy:
    src: docker-compose.yaml
    dest: "{{ jellyfin_config_dir }}/docker-compose.yaml"
    mode: '0644'

- name: Start Jellyfin container with Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ jellyfin_config_dir }}"
    state: present

- name: Add users to jellyfin group
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups: jellyfin
    append: yes
  loop: "{{ jellyfin_users }}"

- name: Download Jellyfin GPG key
  get_url:
    url: https://repo.jellyfin.org/jellyfin_team.gpg.key
    dest: /etc/apt/trusted.gpg.d/jellyfin.asc
    mode: '0644'
  
- name: Add Jellyfin repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/jellyfin.asc] https://repo.jellyfin.org/ubuntu {{ ansible_distribution_release | lower }} main"
    state: present

- name: Update APT again after adding Docker repo
  apt:
    update_cache: yes

- name: Instal HW drivers
  apt:
    name:
      - jellyfin-ffmpeg7
      - intel-opencl-icd
    state: present
  