services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 0:1002
    group_add:
      - 1002
      - 993
    ports:
      - "8096:8096"
    volumes:
      - /etc/jellyfin/config:/config
      - /etc/jellyfin/cache:/cache
      - /data/jellyfin/media/shows:/media/shows
      - /data/jellyfin/media/movies:/media/movies
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    restart: 'unless-stopped'
