services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 0:1002
    group_add:
      - 1002
      - 993
    volumes:
      - /etc/jellyfin/config:/config
      - /etc/jellyfin/cache:/cache
      - /data/@jellyfin/media/shows:/media/shows
      - /data/@jellyfin/media/movies:/media/movies
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.ba.belanec.eu`)"
      - "traefik.http.routers.jellyfin.entrypoints=web"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    restart: 'unless-stopped'
    
networks:
  proxy:
    name: proxy
