services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 0:1002
    ports:
      - "8096:8096"
    volumes:
      - /etc/jellyfin/config:/config
      - /etc/jellyfin/cache:/cache
      - /data/jellyfin/media/shows:/media/shows
      - /data/jellyfin/media/movies:/media/movies
    restart: 'unless-stopped'