- name: Create Btrfs subvolume
  command: "btrfs subvolume create /data/{{ btrfs_subvolume }}"
  args:
    creates: "/data/{{ btrfs_subvolume }}"

- name: Find a field labeled username in an item named librephotos-db in a specific vault
  onepassword.connect.field_info:
    token: "{{ connect_token }}"
    item: librephotos-db
    field: username
    vault: r26avvbe4vsjsx2cnby7jw5unq
  no_log: false  # Turn off logs to avoid logging sensitive data
  register: op_item

- name: Print the field definition
  ansible.builtin.debug:
    msg: "{{ op_item.field }}"