- name: Create Btrfs subvolume
  command: "btrfs subvolume create /data/{{ btrfs_subvolume }}"
  args:
    creates: "/data/{{ btrfs_subvolume }}"

- name: Create nextcloud config directory
  file:
    path: "{{ nextcloud_config_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy Docker Compose file
  copy:
    src: docker-compose.yaml
    dest: "{{ nextcloud_config_dir }}/docker-compose.yaml"
    mode: '0644'

- name: Start librephotos container with Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ nextcloud_config_dir }}"
    state: present