api:
  dashboard: true
  insecure: true
  debug: true

entryPoints:
  web:
    address: ":80"

    http:
      redirections:
        entrypoint:
          to: "websecure"
          scheme: "https"

  websecure:
    address: ":443"
  
  
serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: "/certs"
    watch: true

log:
  filePath: /var/log/traefik/traefik.log

accessLog:
  filePath: /var/log/traefik/traefik.access.log