galaxy_info:
  role_name: ftp_server
  description: Install and configure a simple FTP server using vsftpd
  author: your_name
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - noble
dependencies: []