- name: Create Traefik config directory
  file:
    path: "{{ traefik_config_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Deploy traefik.yml
  copy:
    src: traefik.yml
    dest: "{{ traefik_config_dir }}/traefik.yml"
    owner: root
    group: root
    mode: '0644'

- name: Deploy certs_tls.yml
  copy:
    src: certs_tls.yml
    dest: "{{ traefik_config_dir }}/certs/certs_tls.yml"
    owner: root
    group: root
    mode: '0644'

- name: Copy certificates into Traefik dynamic directory
  copy:
    remote_src: true
    src: "{{ item.src }}"
    dest: "{{ traefik_config_dir }}/certs/{{ item.dest }}"
  loop:
    - { src: '/etc/letsencrypt/live/ba.belanec.eu/cert.pem', dest: 'cert.pem' }
    - { src: '/etc/letsencrypt/live/ba.belanec.eu/privkey.pem', dest: 'privkey.pem' }

- name: Deploy docker-compose.yaml
  copy:
    src: docker-compose.yaml
    dest: "{{ traefik_config_dir }}/docker-compose.yaml"
    owner: root
    group: root
    mode: '0644'

- name: Start Traefik with Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ traefik_config_dir }}"
    state: present